#!/usr/bin/env bash

source $(dirname ${BASH_SOURCE[0]})/armcc-config

function main() {
    local readonly GCC_AT_FLAG='@'
    local readonly ARMCC_VIA_FLAG='--via'
    local arguments="${@}"
    if [[ ! -z "${arguments}" ]]; then
        if [[ "${arguments:0:1}" != '@' ]]; then
            arguments="-${arguments[@]}"
        else
            arguments="${ARMCC_VIA_FLAG} ${arguments:1}"
        fi
    fi
    arguments=${arguments// ${GCC_AT_FLAG}/ ${ARMCC_VIA_FLAG} }
    #echo '[ORIGIN]' armar ${@}
    #echo '[ACTUAL]' armar ${arguments[@]}
    cmd //c ${ARMCCBIN}/armar ${arguments[@]}
}

main "${@}"
