#!/usr/bin/env bash

source $(dirname ${BASH_SOURCE[0]})/armcc-config

function main() {
    local arguments=
    if [[ ! -z "${@}" ]]; then
        arguments="-${@}"
    fi
    cmd //c ${ARMCCBIN}/armar.exe ${arguments[@]}
}

main "${@}"
